import './globals.css'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import Header from './components/Header'
import SupabaseProvider from '@/providers/SupabaseProvider'
import UserProvider from '@/providers/UserProvider'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SupabaseProvider>
          <UserProvider>
        <Header></Header>
        {children}
        </UserProvider>
        </SupabaseProvider>
        
        </body>
    </html>
  )
}
